import React from 'react'
import logo_transparent from '../assets/logo/logo_transparent.png'
import logo from '../assets/logo/logo.png'
import facebook_cover_photo_1 from '../assets/logo/facebook_cover_photo_1.png'
import favicon from '../assets/logo/favicon.png'
import twitter_header_photo_1 from '../assets/logo/twitter_header_photo_1.png'
import rewardrobe1 from '../assets/logo/rewardrobe1.png'
import buy1  from '../assets/hero/buy1.jpeg'
import buy2  from '../assets/hero/buy2.jpeg'
import sell1  from '../assets/hero/sell1.jpeg'
import sell2  from '../assets/hero/sell2.jpeg'
// Sample data for Product in the context
export const product = [
  {
    id: 1,
    images: [
      'https://picsum.photos/200/300',
      'https://picsum.photos/200/300?grayscale',
      'https://picsum.photos/200/300?blur=5',
    ],
    name: 'Eco-friendly T-Shirt',
    price: 29.99,
    previousPrice: 39.99,
    description: 'A comfortable and sustainable t-shirt made from organic cotton.',
    availability: true,
    brand: 'EcoBrand',
    category: 'Apparel',
    sku: 'T-001',
    rating: 4.5,
    reviews: 100,
    size: ['S', 'M', 'L', 'XL'],
    color: ['green', 'blue', 'black'],
    material: 'Organic Cotton',
    weight: '200g',
    tags: ['Eco-Friendly', 'Sustainable'],
    trending: true,
    stockQuantity: 50, // Number of items left in stock
    
  },
  {
    id: 2,
    images: [
      'https://picsum.photos/200/300',
      'https://picsum.photos/200/300?grayscale',
      'https://picsum.photos/200/300?blur=5',
    ],
    name: 'Recycled Cotton Jeans',
    price: 49.99,
    previousPrice: 69.99,
    description: 'Durable jeans made from 100% recycled cotton, stylish and eco-friendly.',
    availability: true,
    brand: 'EcoBrand',
    category: 'Apparel',
    sku: 'J-002',
    rating: 4.0,
    reviews: 80,
    size: ['S', 'M', 'L', 'XL'],
    color: ['blue', 'black'],
    material: 'Recycled Cotton',
    weight: '500g',
    dimensions: 'W30 x L32',
    tags: ['Eco-Friendly', 'Sustainable'],
    discount: true,
    stockQuantity: 30,
    productURL: '/products/recycled-cotton-jeans',
  },
  {
    id: 3,
    images: [
      'https://picsum.photos/200/300',
      'https://picsum.photos/200/300?grayscale',
      'https://picsum.photos/200/300?blur=5',
    ],
    name: 'Sustainable Sneakers',
    price: 79.99,
    previousPrice: 99.99,
    description: 'Sneakers made from recycled materials, offering comfort and style.',
    availability: true,
    brand: 'EcoBrand',
    category: 'Footwear',
    sku: 'S-003',
    rating: 4.7,
    reviews: 120,
    size: ['6', '7', '8', '9', '10'],
    color: ['white', 'gray'],
    material: 'Recycled Materials',
    weight: '800g',
    dimensions: 'N/A',
    tags: ['Eco-Friendly', 'Sustainable', 'Comfort'],
    discount: false,
    stockQuantity: 70,
    productURL: '/products/sustainable-sneakers',
  },
  {
    id: 4,
    images: [
      'https://picsum.photos/200/300',
      'https://picsum.photos/200/300?grayscale',
      'https://picsum.photos/200/300?blur=5',
    ],
    name: 'Organic Cotton Hoodie',
    price: 59.99,
    previousPrice: 79.99,
    description: 'A cozy hoodie made from 100% organic cotton.',
    availability: true,
    brand: 'EcoBrand',
    category: 'Apparel',
    sku: 'H-004',
    rating: 4.3,
    reviews: 90,
    size: ['S', 'M', 'L', 'XL'],
    color: ['gray', 'black'],
    material: 'Organic Cotton',
    weight: '700g',
    dimensions: 'L: 30", W: 20" (Size M)',
    tags: ['Eco-Friendly', 'Sustainable'],
    discount: true,
    stockQuantity: 40,
    productURL: '/products/organic-cotton-hoodie',
  },
  {
    id: 5,
    images: [
      'https://picsum.photos/200/300',
      'https://picsum.photos/200/300?grayscale',
      'https://picsum.photos/200/300?blur=5',
    ],
    name: 'Bamboo Sunglasses',
    price: 19.99,
    previousPrice: 29.99,
    description: 'Eco-friendly sunglasses made from sustainable bamboo.',
    availability: true,
    brand: 'EcoBrand',
    category: 'Accessories',
    sku: 'B-005',
    rating: 4.8,
    reviews: 50,
    size: ['One size'],
    color: ['brown', 'black'],
    material: 'Bamboo',
    weight: '150g',
    dimensions: 'N/A',
    tags: ['Eco-Friendly', 'Sustainable', 'Fashion'],
    discount: false,
    stockQuantity: 100,
    productURL: '/products/bamboo-sunglasses',
  },
  {
    id: 6,
    images: [
      'https://picsum.photos/200/300',
      'https://picsum.photos/200/300?grayscale',
      'https://picsum.photos/200/300?blur=5',
    ],
    name: 'Plant-based Jacket',
    price: 89.99,
    previousPrice: 119.99,
    description: 'A warm jacket made from plant-based materials.',
    availability: true,
    brand: 'EcoBrand',
    category: 'Outerwear',
    sku: 'J-006',
    rating: 4.6,
    reviews: 60,
    size: ['S', 'M', 'L', 'XL'],
    color: ['green', 'black'],
    material: 'Plant-based Fabrics',
    weight: '1kg',
    dimensions: 'L: 28", W: 24" (Size M)',
    tags: ['Eco-Friendly', 'Sustainable', 'Winter Wear'],
    discount: false,
    stockQuantity: 20,
    productURL: '/products/plant-based-jacket',
  },
  {
    id: 7,
    images: [
      'https://picsum.photos/200/300',
      'https://picsum.photos/200/300?grayscale',
      'https://picsum.photos/200/300?blur=5',
    ],
    name: 'Recycled Backpack',
    price: 39.99,
    previousPrice: 49.99,
    description: 'Durable backpack made from recycled materials, perfect for daily use.',
    availability: true,
    brand: 'EcoBrand',
    category: 'Accessories',
    sku: 'B-007',
    rating: 4.2,
    reviews: 40,
    size: ['One size'],
    color: ['blue', 'black'],
    material: 'Recycled Materials',
    weight: '600g',
    dimensions: '12" x 16" x 6"',
    tags: ['Eco-Friendly', 'Sustainable'],
    discount: true,
    stockQuantity: 50,
    productURL: '/products/recycled-backpack',
  },
  {
    id: 8,
    images: [
      'https://picsum.photos/200/300',
      'https://picsum.photos/200/300?grayscale',
      'https://picsum.photos/200/300?blur=5',
    ],
    name: 'Vegan Leather Wallet',
    price: 25.99,
    previousPrice: 35.99,
    description: 'A sleek wallet made from cruelty-free vegan leather.',
    availability: true,
    brand: 'EcoBrand',
    category: 'Accessories',
    sku: 'W-008',
    rating: 4.4,
    reviews: 70,
    size: ['One size'],
    color: ['brown', 'black'],
    material: 'Vegan Leather',
    weight: '200g',
    dimensions: '4.5" x 3.5"',
    tags: ['Eco-Friendly', 'Sustainable'],
    discount: false,
    stockQuantity: 80,
    productURL: '/products/vegan-leather-wallet',
  },
  {
    id: 9,
    images: [
      'https://picsum.photos/200/300',
      'https://picsum.photos/200/300?grayscale',
      'https://picsum.photos/200/300?blur=5',
    ],
    name: 'Fair Trade Socks',
    price: 9.99,
    previousPrice: 15.99,
    description: 'Comfy socks made from fair trade organic cotton.',
    availability: true,
    brand: 'EcoBrand',
    category: 'Apparel',
    sku: 'S-009',
    rating: 4.7,
    reviews: 30,
    size: ['S', 'M', 'L'],
    color: ['white', 'black'],
    material: 'Fair Trade Organic Cotton',
    weight: '100g',
    dimensions: 'N/A',
    tags: ['Eco-Friendly', 'Sustainable'],
    discount: true,
    stockQuantity: 150,
    productURL: '/products/fair-trade-socks',
  },
  {
    id: 10,
    images: [
      'https://picsum.photos/200/300',
      'https://picsum.photos/200/300?grayscale',
      'https://picsum.photos/200/300?blur=5',
    ],
    name: 'Sustainable Water Bottle',
    price: 15.99,
    previousPrice: 20.99,
    description: 'A stainless steel water bottle designed to be eco-friendly.',
    availability: true,
    brand: 'EcoBrand',
    category: 'Accessories',
    sku: 'B-010',
    rating: 4.9,
    reviews: 150,
    size: ['One size'],
    color: ['blue', 'green', 'black'],
    material: 'Stainless Steel',
    weight: '300g',
    dimensions: '2.5" x 8.5"',
    tags: ['Eco-Friendly', 'Sustainable', 'Hydration'],
    discount: false,
    stockQuantity: 200,
    productURL: '/products/sustainable-water-bottle',
  },
  {
    id: 11,
    images: [
      'https://picsum.photos/200/300',
      'https://picsum.photos/200/300?grayscale',
      'https://picsum.photos/200/300?blur=5',
    ],
    name: 'Biodegradable Phone Case',
    price: 24.99,
    previousPrice: 30.99,
    description: 'A phone case made from biodegradable materials.',
    availability: true,
    brand: 'EcoBrand',
    category: 'Accessories',
    sku: 'C-011',
    rating: 4.3,
    reviews: 120,
    size: ['One size'],
    color: ['gray', 'black'],
    material: 'Biodegradable Plastic',
    weight: '150g',
    dimensions: 'N/A',
    tags: ['Eco-Friendly', 'Sustainable', 'Tech Accessories'],
    discount: true,
    stockQuantity: 60,
    productURL: '/products/biodegradable-phone-case',
  },
  {
    id: 12,
    images: [
      'https://picsum.photos/200/300',
      'https://picsum.photos/200/300?grayscale',
      'https://picsum.photos/200/300?blur=5',
    ],
    name: 'Upcycled Wool Scarf',
    price: 34.99,
    previousPrice: 49.99,
    description: 'A scarf made from upcycled wool, perfect for colder months.',
    availability: true,
    brand: 'EcoBrand',
    category: 'Accessories',
    sku: 'S-012',
    rating: 4.6,
    reviews: 50,
    size: ['One size'],
    color: ['gray', 'black'],
    material: 'Upcycled Wool',
    weight: '200g',
    dimensions: 'N/A',
    tags: ['Eco-Friendly', 'Sustainable', 'Winter Wear'],
    discount: false,
    stockQuantity: 80,
    productURL: '/products/upcycled-wool-scarf',
  },
];

export const assets = {
    logo_transparent,
    logo,
    facebook_cover_photo_1,
    favicon,
    twitter_header_photo_1,
    rewardrobe1,
    sell1,
    sell2,
    buy1,
    buy2

}